from collections import namedtuple

# List of artifacts in the order of resources: 0-37
Artifact = namedtuple('Artifact', ['name'], module='fhomm.game')

# TODO: support translations!
ARTIFACTS = [
    Artifact("Ultimate Book of Knowledge"),
    Artifact("Ultimate Sword of Dominion"),
    Artifact("Ultimate Cloack of Protection"),
    Artifact("Ultimate Wand of Power"),
    Artifact("Arcane Necklace"),
    Artifact("Caster's Bracelet"),
    Artifact("Mage's Ring"),
    Artifact("Witch's Broach"),
    Artifact("Medal of Valor"),
    Artifact("Medal of Courage"),
    Artifact("Medal of Honor"),
    Artifact("Medal of Distinction"),
    Artifact("Fizbin of Misfortune"),
    Artifact("Thunder Mace"),
    Artifact("Armored Gauntlet"),
    Artifact("Defender Helm"),
    Artifact("Giant Flail"),
    Artifact("Ballista of Quickness"),
    Artifact("Stealth Shield"),
    Artifact("Dragon Sword"),
    Artifact("Power Axe"),
    Artifact("Divine Breastplate"),
    Artifact("Minor Scroll"),
    Artifact("Major Scroll"),
    Artifact("Superior Scroll"),
    Artifact("Foremost Scroll"),
    Artifact("Endless Sack"),
    Artifact("Endless Bag"),
    Artifact("Endless Purse"),
    Artifact("Nomad's Boots"),
    Artifact("Traveler's Boots"),
    Artifact("Rabbit's Foot"),
    Artifact("Golden Horseshoe"),
    Artifact("Gambler's Coin"),
    Artifact("Lucky Clover"),
    Artifact("True Compass of Mobility"),
    Artifact("Astrolabe"),
    Artifact("Magic Book"),
]
